version: '3.8'

services:
  fastqc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastqc_container
    volumes:
      - fastqc_results:/results
      - ./input:/input:ro
    networks:
      - fastqc_network
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      CLASSPATH: /usr/local/FastQC:/usr/local/FastQC/htsjdk.jar:/usr/local/FastQC/jbzip2-0.9.jar:/usr/local/FastQC/cisd-jhdf5>
    command: /input/SRR8786200_1.fastq.gz -o /results

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - fastqc_results:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    networks:
      - fastqc_network

volumes:
  fastqc_results:

networks:
  fastqc_network:
